name = "BuildMachines"
uuid = "bcdc6e61-a161-4045-bb60-3c0bf2ca02b4"
authors = ["Dilum Aluthge"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
